/*
 * Copyright (c) 2020 - present Cloudogu GmbH
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

plugins {
  id 'org.scm-manager.smp' version '0.17.0'
}

dependencies {
  plugin "sonia.scm.plugins:scm-rest-legacy-plugin:3.0.0"
  plugin "sonia.scm.plugins:scm-activity-plugin:3.0.0"
  plugin "sonia.scm.plugins:scm-statistic-plugin:3.0.0"
}

scmPlugin {
  scmVersion = "3.0.0"
  displayName = "Cockpit"
  description = "Offers a subset of the SCM-Manager v1 REST API for the use of Cloudogu Ecosystem Cockpit"
  author = "Cloudogu GmbH"
  category = "Legacy Support"
  avatarUrl = '/images/cockpit-legacy-logo.png'

  openapi {
    packages = [
      "sonia.scm.legacy"
    ]
  }
}
